# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/jekyll" # the subpath of your site, e.g. /blog/
url: "http://allenwrenches.github.io/jekyll" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Collections
collections:
  Chapter1:
    output: true
    permalink: :path/
  Chapter2:
    output: true
    permalink: :path/
  Chapter3:
    output: true
    permalink: :path/
    
render:
  - Chapter1
  - Chapter2
  - Chapter3

# Build settings
markdown: kramdown

permalink: pretty
prose:
  media: 'jekyll/media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "chapter"
        field:
          element: "select"
          label: "Select Chapter"
          placeholder: "Select Chapter"
          options:
            - name: "Chapter 1"
              value: "chapter1"
            - name: "Chapter 2"
              value: "chapter2"
            - name: "Chapter 3"
              value: "chapter3"
      - name: "InNav"
        field:
          element: "button"
          label: "SubNav"
          on: "on"
          off: "off"
      - name: "layout"
        field:
          element: "select"
          label: "Layout"
          placeholder: "Choose Layout"
          options:
            - name: "Content"
              value: "content"
            - name: "Accordion"
              value: "accordion"
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"